### ISSUE TITLE
Edited Notice is not working as expected.

### ISSUE THREAD

**Issue by VivekCodees** [joplangmaring/AIDS#15]
**Description:**
The functionality for fetching and editing notices works as expected up to a point. I can:
i. Fetch all notices without any issues.
ii. Click on the "Edit" button and see the correct notice data being loaded into the form for editing.
However, after making changes to the notice and submitting the edits, the changes are not saved successfully. The system does not persist the updated data, and the notice remains unchanged upon refreshing or re-fetching the notices.

**Steps to Reproduce:**

i. Fetch the list of notices.
ii. Click on the "Edit" button for any notice.
iii. Modify the notice data in the edit form and submit the changes.
iv. Observe that the updated notice data is not saved or reflected in the system.

**Expected Behavior:**
After editing a notice and submitting the changes, the updated data should be saved successfully and reflected in the notice list.

**Actual Behavior:**
The edited notice is not saved, and the changes are not reflected in the notice list.

Kindly provide a fix for this issue at the earliest

**Comment by webgaurav02** [comment]
I'll work on this issue. Can you please assign it to me.
